### ISSUE TITLE
sg language not available

### ISSUE THREAD

**Issue by smilemushroom** [yurimalheiros/senticnetapi#12]
hi, I realised that there is a sg language that is not available (http://sentic.net/singlish-senticnet.zip), is it possible to make it available?

**Comment by yurimalheiros** [comment]
Hi! That's great! 

You should contact Erik from the SenticNet team (http://sentic.net/team/) about the support for a new language. 

I am not part of the SenticNet team, I only develop this lib to use their data, so I think it is better to check this with them.

Thank you for the contact.

**Comment by smilemushroom** [comment]
Hi Yuri,
I see, thank you :)
