### ISSUE TITLE
How many moodtags does senticnet include?

### ISSUE THREAD

**Issue by bjtuweb-12283027** [yurimalheiros/senticnetapi#13]
Sorry for bothering.I googled a lot and didn't find the moodtags description of senticnet5.
Could you tell me how many moodtags does it include?

**Comment by yurimalheiros** [comment]
I am not sure. Accordingly to the SenticNet website, the moodtags are based on the HourGlass model. Check Figure 4 and Table 3 of this paper: https://sentic.net/hourglass-of-emotions.pdf.

I checked the concepts and I found that some categories in the HourGlass model does not have any entry in the SenticNet.
