### ISSUE TITLE
Stop iteration error

### ISSUE THREAD

**Issue by tanayz** [yurimalheiros/senticnetapi#3]
Hi

I tried using both version 0.3.3 (through pip) and version 0.4.1 (using git),hoever in both cases I'm seeing following error while running code from example.py.Let me know if there is a work around there.

from senticnet.senticnet import Senticnet

sn = Senticnet()
concept_info = sn.concept('love')

Traceback (most recent call last):

  File "<ipython-input-1-0f22a15849a8>", line 4, in <module>
    concept_info = sn.concept('love')

  File "/home/tanay/anaconda/lib/python2.7/site-packages/senticnet-0.4.1-py2.7.egg/senticnet/senticnet.py", line 24, in concept
    result["polarity"] = self.polarity(concept, parsed_graph)

  File "/home/tanay/anaconda/lib/python2.7/site-packages/senticnet-0.4.1-py2.7.egg/senticnet/senticnet.py", line 75, in polarity
    return parsed_graph.objects(predicate=URIRef(predicate_uri)).next().toPython()

StopIteration

**Comment by yurimalheiros** [comment]
I reproduced this bug.

Sometimes Senticnet project change some stuff in the RDF and it may break the API. I am investigating the error. 

Thank you for the report.

**Comment by ptsantar** [comment]
I think the problem is in the namespace declarations.
It is : 
    <rdf:RDF xmlns:rdf="http://w3.org/1999/02/22-rdf-syntax-ns#">
But it should be : 
    <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
It seemed to work for me with Java + Jena. 
Credits to http://stackoverflow.com/questions/24527728/w3c-validator-cant-process-rdf-xml

**Comment by yurimalheiros** [comment]
You're right. I tested exactly what you said and it worked when I used "http://www.w3.org/1999/02/22-rdf-syntax-ns#" instead of "http://w3.org/1999/02/22-rdf-syntax-ns#"

I will contact the creators of Senticnet to try to solve this.

Thank you very much for your time and help.

**Comment by yurimalheiros** [comment]
Dr. Cambria answered me, and he will fix this problem. We just need to wait a little :smiley:

**Comment by swatisanagar** [comment]
I'm facing the same problem.  Is their any alternate way? pl. suggest

**Comment by tanayz** [comment]
Here is a hack I created on this,the main idea is to fetch the result from webapi(as that is working).I believe it can also be used on other metrics than polarity with minor tweak.

from __future__ import division
import rdflib
from nltk.corpus import stopwords
import extraction,requests
import urllib2

concept_base_uri = "http://sentic.net/api/en/concept/"
senticapi_base_uri = "http://sentic.net/api"

# public methods

def polarity(conceptstr, parsed_graph=None):
    """
    Return the polarity of a concept.
    If you pass a parsed graph, the method do not load the rdf again.
    """
    concept_polarity_uri = concept_base_uri+conceptstr+"/polarity"
#    predicate_uri = senticapi_base_uri+"polarity"

    if parsed_graph is None:
        try:
            graph = rdflib.Graph()
            parsed_graph = graph.parse(concept_polarity_uri, format="xml")
            return output(concept_polarity_uri)

        except Exception:
            return 0


def output(url):
    response = urllib2.urlopen(url)
    html = response.read()
    
    html=html.replace('w3.org','www.w3.org')
    
    graph = rdflib.Graph()
    parsed_graph = graph.parse(data=html, format="xml")
    #parsed_graph.objects(predicate=URIRef(predicate_uri))
    
    
    result = []
     
    for s, p, o in parsed_graph:
         if type(o) == rdflib.term.Literal:
             result.append(o.toPython())

**Comment by tanayz** [comment]
I've created a working version of the api that returns all the concepts,including semantics,sentics and polarity avoiding the w3 error.The owner might need to check the pull request.Here is my the link to my github repo of this working version.
https://github.com/tanayz/senticnetapi

**Comment by yurimalheiros** [comment]
I linked your repo on README, so more people can find your solution while the RDF problem is not solved.

**Comment by vidyasagarsvn** [comment]
Hi @yurimalheiros ,

I am afraid the code for the workaround from @tanayz is not efficient and elegant because of the following reasons
1. The _rdflib.Graph.parse_ method is called twice in the methods Senticnet._polarity_ and Senticnet._sentics_. This is not necessary.
2. The input parameter _parsed_graph_ is ignored in all the methods Senticnet._polarity_, Senticnet._sentics_ and Senticnet._semantics_ (since _self.output_ is called anyway)
3. If the RDF returned by the Senticnet API already contains _www.w3.org_, the code in _self.output_ changes it to _www.www.w3.org_. This is a bug.

We don't actually need the method _Senticnet.output_. All we need to do is get the data from SenticNet  API, replace _http://w3.org_ with _http://www.w3.org_ and change the value of _self.senticnet_base_uri_ to _http://sentic.net_. This requires very **minimal** changes to the original source code.

I have forked this repository and made the same changes at https://github.com/vidyasagarsvn/senticnetapi.

**Comment by yurimalheiros** [comment]
Hi @vidyasagarsvn, that's really great. Thank you.

What do you think about a pull request to update the main repository?

I added the note in README 10 months ago and until now the senticnet mantainers did not fix the URL problem, so, I think it will be good to update the main senticnetapi repository with your solution.

**Comment by vidyasagarsvn** [comment]
Should i create a pull request to push the code into the main repository's 'master'?

**Comment by yurimalheiros** [comment]
Yes, @vidyasagarsvn, and thanks again.

**Comment by vidyasagarsvn** [comment]
Done. Please review and commit the changes.

I have a couple more questions though,
1) Are you planning to upload the latest package into PyPI?
2) The code doesn't work for python >= 3 because in Python >= 3
    a) The function <generator>.next() is replaced by a free function next(<generator>)
    b) urllib2.urlopen is now urllib.request.urlopen
    If one plans to fix this, I am thinking a **separate branch** is required. The package for Python >= 3 should be built and uploaded into PyPI

**Comment by yurimalheiros** [comment]
I just saw the pull request, and I commented there.

About your questions...

1. For sure.
2. Yes, I made the code for Python 2. I 100% agree that we need a Python 3 version. If you want to work on this I will be very glad, but if you don't have time right now, I can code this version soon.

**Comment by vidyasagarsvn** [comment]
I can work on modifying the code for Python 3. Do you think its better to create a separate branch or use some if-else code in the master to make sure it works for both Python 2 and 3? I was thinking about the latter because I don't foresee more changes to the rest of this code.

**Comment by yurimalheiros** [comment]
Cool. In this case, we can create PyPI package for both Python 2 and 3?

**Comment by vidyasagarsvn** [comment]
Yes. Once i make the changes for Python 3, I will let you know.
