### ISSUE TITLE
Support Python 3

### ISSUE THREAD

**Issue by yurimalheiros** [yurimalheiros/senticnetapi#8]

**Comment by mmirtalaie** [comment]
Hi, 
Thanks for sharing your repository. I'm so new to python. I have problem in using senticnet for multiwords like "very bad". I have tried it using _ instead of space but still receiving errors. May u plz help me?

**Comment by yurimalheiros** [comment]
Hi @mmirtalaie, I think there is not a concept "very_bad" in the SenticNet. You can find the concept "bad".
