### ISSUE TITLE
Senticnet for sentences

### ISSUE THREAD

**Issue by mmirtalaie** [yurimalheiros/senticnetapi#9]
Hi, 
Can we use this package for analysing sentences? I can only use it for single words like 'good'. While in their demo you can use it to do sentiment analysing a whole sentence. Does this package have this ability? If yes, can you plz provide a sample code?

**Comment by yurimalheiros** [comment]
Hi @mmirtalaie. This package only provides access to the data of Senticnet. 
If you want to analyze whole sentences, I recommend to look the publications of the Senticnet team: http://sentic.net/publications/. 

Also, you can test this simple approach: 1) identify the concepts in the sentence; 2) get the polarity of them in the senticnet using this package; 3) calculate an average or maybe sum all values.

Note: I am not part of the Senticnet team.

**Comment by daliu** [comment]
Hi there, I've created a build-off of this that allows sentence analysis! I hope it's useful!

https://github.com/daliu/sentic/tree/master/sentic

**Comment by yurimalheiros** [comment]
Does it calculate the average of the sentics?

**Comment by daliu** [comment]
Yup, that's all it does, just develops a normalized average of the measurements across the text.
